apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: registryNamespace
        description: the ibmcloud registry namespace
      - name: imageName
        description: the base image name
        default: "hello-containers-tekton"
      - name: registryRegion
        description: the ibmcloud registry region        
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY hello world";
          git clone -q -b $REVISION $REPOSITORY .;
    - name: pre-build-check
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: REGION
          value: $(inputs.params.registryRegion)
        - name: HOME
          value: "/root"
        - name: REGISTRY_NAMESPACE
          value: $(inputs.params.registryNamespace)
        - name: IMAGE_NAME
          value: $(inputs.params.imageName)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $API -r $REGION;
          export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
          source pre-build-check.sh;
      volumeMounts:
        - mountPath: /step-mount
          name: task-volume
    - name: build-docker-image
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: REGION
          value: $(inputs.params.registryRegion)
        - name: HOME
          value: "/root"
        - name: REGISTRY_NAMESPACE
          value: $(inputs.params.registryNamespace)
        - name: IMAGE_NAME
          value: $(inputs.params.imageName)
        - name: ARCHIVE_DIR
          value: "/artifacts"
        - name: BUILD_NUMBER
          value: "0"
        - name: GIT_BRANCH
          value: $(inputs.params.revision)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $API -r $REGION;
          export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh";
          export GIT_COMMIT=$(git rev-parse HEAD);
          export REGISTRY_URL=$(ibmcloud cr info | sed "2q;d" | awk '{for(i=1;i<=NF;i++) if ($i=="Registry") print $(i+1)}');
          source build-docker-image.sh;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: validate-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: registryRegion
        description: the ibmcloud registry region           
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          git clone -q -b $REVISION $REPOSITORY .;
    - name: check-vulnerabilities
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: HOME
          value: "/root"
        - name: REGION
          value: $(inputs.params.registryRegion)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $API -r $REGION;
          while read line; do export $line; done < /artifacts/build.properties;
          cp /artifacts/build.properties .;
          source check-vulnerabilities.sh || true;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
      - name: repository
        description: the git repo
      - name: revision
        description: the revision
        default: master
      - name: apikey
        description: the ibmcloud api key
      - name: api
        description: the ibmcloud api endpoint
        default: "https://cloud.ibm.com"
      - name: deployment-file
        default: deployment.yml
      - name: clusterNamespace
        default: prod
      - name: cluster
        description: The IBM Cloud Kubernetes cluster name
      - name: clusterRegion
        description: The IBM Cloud Kubernetes cluster region
  steps:
    - name: clone-repo
      image: alpine/git
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: REVISION
          value: $(inputs.params.revision)
      command: ["/bin/sh", "-c"]
      args:
        - set -e -o pipefail;
          echo "Cloning $REPOSITORY";
          git clone -q -b $REVISION $REPOSITORY .;
    - name: pre-deploy-check
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: REGION
          value: $(inputs.params.clusterRegion)
        - name: HOME
          value: "/root"
        - name: DEPLOYMENT_FILE
          value: $(inputs.params.deployment-file)
        - name: CLUSTER_NAMESPACE
          value: $(inputs.params.clusterNamespace)
        - name: PIPELINE_KUBERNETES_CLUSTER_NAME
          value: $(inputs.params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $API -r $REGION;
          $(ibmcloud ks cluster config --cluster "${PIPELINE_KUBERNETES_CLUSTER_NAME}" --export);
          while read line; do export $line; done < /artifacts/build.properties;
          cp /artifacts/build.properties .;
          source pre-deploy-check.sh;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
    - name: deploy-to-kubernetes
      image: ibmcom/pipeline-base-image
      env:
        - name: IBMCLOUD_API_KEY
          value: $(inputs.params.apikey)
        - name: API
          value: $(inputs.params.api)
        - name: REGION
          value: $(inputs.params.clusterRegion)
        - name: HOME
          value: "/root"
        - name: DEPLOYMENT_FILE
          value: $(inputs.params.deployment-file)
        - name: CLUSTER_NAMESPACE
          value: $(inputs.params.clusterNamespace)
        - name: PIPELINE_KUBERNETES_CLUSTER_NAME
          value: $(inputs.params.cluster)
      command: ["/bin/bash", "-c"]
      args:
        - set -e -o pipefail;
          ibmcloud login -a $API -r $REGION;
          $(ibmcloud ks cluster config --cluster "${PIPELINE_KUBERNETES_CLUSTER_NAME}" --export);
          while read line; do export $line; done < /artifacts/build.properties;
          cp /artifacts/build.properties .;
          source deploy-to-kubernetes.sh;
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
      
